# Generated by Django 2.1 on 2023-02-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField()),
                ('end_date', models.DateField()),
                ('pricing', models.FloatField()),
                ('rating', models.IntegerField()),
                ('status', models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished'), ('U', 'Under negotiation')], max_length=1)),
            ],
        ),
    ]
