# Generated by Django 2.1 on 2023-03-01 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0002_client_freelancer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Has_service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Score_rating', models.FloatField()),
                ('Delay_compliance', models.FloatField()),
                ('status', models.CharField(choices=[('E', 'Enabled'), ('D', 'Disabled'), ('P', 'Pending')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Available', models.BooleanField(default=False)),
                ('Basic_price', models.FloatField()),
                ('release_date', models.DateField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Service_skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('required_grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('discription', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Test_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='pricing_proposal',
            field=models.FloatField(),
        ),
        migrations.AddField(
            model_name='test_result',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Freelancer'),
        ),
        migrations.AddField(
            model_name='test_result',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Skill'),
        ),
        migrations.AddField(
            model_name='skill',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Test'),
        ),
        migrations.AddField(
            model_name='service_skill',
            name='skill',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Skill'),
        ),
        migrations.AddField(
            model_name='has_service',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Freelancer'),
        ),
        migrations.AddField(
            model_name='has_service',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Service'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App_beta.Service'),
            preserve_default=False,
        ),
    ]
