# Generated by Django 2.1 on 2023-03-01 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0003_auto_20230301_2001'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_proposal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_proposal', models.FloatField()),
                ('completion_duration_proposal', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('E', 'Accepted'), ('R', 'Rejected'), ('P', 'Pending')], max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='client',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='Project',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='completion_duration_proposal',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='pricing_proposal',
        ),
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App_beta.Client'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='App_beta.Freelancer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price_proposal',
            name='freelancer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Freelancer'),
        ),
        migrations.AddField(
            model_name='price_proposal',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_beta.Project'),
        ),
    ]
