# Generated by Django 2.1 on 2023-03-06 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0004_auto_20230301_2054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='Available',
            new_name='available',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='Basic_price',
            new_name='basic_price',
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=100),
        ),
    ]
