# Generated by Django 2.1 on 2023-03-08 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0005_auto_20230306_1823'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(default=True, max_length=1000),
            preserve_default=False,
        ),
    ]
