# Generated by Django 2.1 on 2023-03-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0006_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default=True, max_length=100),
            preserve_default=False,
        ),
    ]
