# Generated by Django 2.1 on 2023-03-11 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0009_auto_20230311_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
