# Generated by Django 2.1 on 2023-03-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0012_auto_20230311_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='image',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='image',
        ),
    ]
