# Generated by Django 2.1 on 2023-03-11 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0013_auto_20230311_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
