# Generated by Django 2.2.28 on 2023-04-09 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0015_auto_20230326_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='title',
        ),
    ]
