# Generated by Django 2.2.28 on 2023-04-21 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0016_auto_20230409_1618'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='expected_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='freelancer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_beta.Freelancer'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pricing',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished'), ('U', 'Under negotiation')], default=1, max_length=1),
        ),
    ]
