# Generated by Django 2.2.28 on 2023-04-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0018_auto_20230421_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('O', 'Ongoing'), ('F', 'Finished'), ('U', 'Under negotiation')], default=3, max_length=1),
        ),
    ]
