# Generated by Django 2.2.28 on 2023-05-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0019_auto_20230429_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tool_name', models.CharField(max_length=25)),
            ],
        ),
    ]
