# Generated by Django 2.2.28 on 2023-05-07 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0020_tool'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App_beta.Tool'),
        ),
    ]
