# Generated by Django 2.2.28 on 2023-05-07 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0021_project_tool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tool',
        ),
        migrations.AddField(
            model_name='project',
            name='tool',
            field=models.ManyToManyField(blank=True, null=True, to='App_beta.Tool'),
        ),
    ]
