# Generated by Django 2.2.28 on 2023-05-29 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0022_auto_20230507_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='tool',
            field=models.ManyToManyField(to='App_beta.Tool'),
        ),
    ]
