# Generated by Django 2.2.28 on 2023-06-28 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_beta', '0025_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
